### ISSUE TITLE
None capabilities as Error

### ISSUE THREAD

**Issue by TA2k** [nbogojevic/midea-beautiful-air#11]
When I requesting status from an Air Conditioner via cloud I receiving
When request the capabilities
```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mp-prod.appsmb.com:443
DEBUG:urllib3.connectionpool:https://mp-prod.appsmb.com:443 "POST /mas/v5/app/proxy?alias=/v1/appliance/transparent/send HTTP/1.1" 200 26
DEBUG:midea_beautiful.cloud:HTTP response text: {"code":"1000","msg":null}
DEBUG:midea_beautiful.cloud:HTTP response: {'code': '1000', 'msg': None}
midea_beautiful.exceptions.CloudError: Midea cloud API error: None (1000)
```
I'm not sure is this really an error or normal response for no capabilities

I saw also ```Creating DehumidifierAppliance``` in the log for an Air Conditioner for Comfee Cool 7000-1

**Comment by TA2k** [comment]
```
 File "/lan.py", line 788, in identify
    responses = self._status(cmd, cloud if use_cloud else None)
  File "/lan.py", line 538, in _status
    responses = cloud.appliance_transparent_send(self.appliance_id, data)
  File "/cloud.py", line 526, in appliance_transparent_send
    response = self.api_request(
  File "/cloud.py", line 302, in api_request
    self.handle_api_error(int(payload[error_code_tag]), payload["msg"])
  File "/cloud.py", line 645, in handle_api_error
    handler()
  File "/cloud.py", line 630, in cloud_error
    raise CloudError(error, message)
```

**Comment by TA2k** [comment]
@nbogojevic Do you plan to change this or should I change the way of updating?

**Comment by TA2k** [comment]
@nbogojevic Do you accept a PR to solve the issue?

**Comment by dezsocsete** [comment]
same thing.

Code:
```
from midea_beautiful import appliance_state, connect_to_cloud, find_appliances
from midea_beautiful.midea import (APPLIANCE_TYPE_AIRCON)

bedroom_appliance_id = 153
cloud = connect_to_cloud(
    account="",  # Account e-mail
    password="",  # Account password
    appname="MSmartHome"
)
appliances = cloud.list_appliances()
for appliance in appliances:
    print(f"{appliance!r}")
    bedroom_appliance = appliance_state( 
        cloud=cloud,
        use_cloud=True,
        appliance_type=APPLIANCE_TYPE_AIRCON,
        appliance_id=appliance["id"]
    )
    print(f"{bedroom_appliance!r}")

```

output:
```
kadadev@Juhaszs-MacBook-Air midea % python3 main.py                                                                                                    
{'id': '15283, 'name': 'Tetőtér', 'sn': '000000P0000000Q1', 'type': '0xAC', 'modelNumber': '44204'}
Error getting device capabilities for sn=None id=15393162819**** address=None version=3, cause Midea cloud API error: None (1000)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/midea_beautiful/lan.py", line 793, in identify
    responses = self._status(cmd, cloud if use_cloud else None)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/midea_beautiful/lan.py", line 538, in _status
    responses = cloud.appliance_transparent_send(self.appliance_id, data)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/midea_beautiful/cloud.py", line 529, in appliance_transparent_send
    response = self.api_request(
        "/v1/appliance/transparent/send",
        {"order": order, "funId": "0000", "applianceId": appliance_id},
    )
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/midea_beautiful/cloud.py", line 304, in api_request
    self.handle_api_error(int(payload[error_code_tag]), payload["msg"])
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/midea_beautiful/cloud.py", line 648, in handle_api_error
    handler()
    ~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/midea_beautiful/cloud.py", line 633, in cloud_error
    raise CloudError(error, message)
midea_beautiful.exceptions.CloudError: Midea cloud API error: None (1000)
Traceback (most recent call last):
  File "/Users/kadadev/midea/main.py", line 13, in <module>
    bedroom_appliance = appliance_state(
        cloud=cloud,
    ...<2 lines>...
        appliance_id=bedroom_appliance_id,  # Appliance id obtained from Midea API
    )
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/midea_beautiful/lan.py", line 1047, in appliance_state
    appliance.identify(cloud, use_cloud)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/midea_beautiful/lan.py", line 831, in identify
    self.refresh(cloud if use_cloud else None)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/midea_beautiful/lan.py", line 381, in refresh
    responses = self._status(cmd, cloud)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/midea_beautiful/lan.py", line 538, in _status
    responses = cloud.appliance_transparent_send(self.appliance_id, data)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/midea_beautiful/cloud.py", line 529, in appliance_transparent_send
    response = self.api_request(
        "/v1/appliance/transparent/send",
        {"order": order, "funId": "0000", "applianceId": appliance_id},
    )
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/midea_beautiful/cloud.py", line 304, in api_request
    self.handle_api_error(int(payload[error_code_tag]), payload["msg"])
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/midea_beautiful/cloud.py", line 648, in handle_api_error
    handler()
    ~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/midea_beautiful/cloud.py", line 633, in cloud_error
    raise CloudError(error, message)
midea_beautiful.exceptions.CloudError: Midea cloud API error: None (1000)
```

Did you solve the issue?
