### ISSUE TITLE
ImportError: libffi.so.7: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by feliutg** [nbogojevic/midea-beautiful-air#12]
Hi, I am stuck running midea-beautiful-air-cli --help or any other command. I updated my raspberry pi and for long time I have installed and running fine python 3.9.5.
Have anyone seen this error before?

pi@raspberrypi:~ $ midea-beautiful-air-cli --help
Traceback (most recent call last):
  File "/home/pi/.local/bin/midea-beautiful-air-cli", line 5, in <module>
    from midea_beautiful.cli import cli
  File "/home/pi/.local/lib/python3.9/site-packages/midea_beautiful/__init__.py", line 6, in <module>
    from midea_beautiful.cloud import MideaCloud
  File "/home/pi/.local/lib/python3.9/site-packages/midea_beautiful/cloud.py", line 16, in <module>
    from midea_beautiful.crypto import Security
  File "/home/pi/.local/lib/python3.9/site-packages/midea_beautiful/crypto.py", line 17, in <module>
    from midea_beautiful.midea import (
  File "/home/pi/.local/lib/python3.9/site-packages/midea_beautiful/midea.py", line 58, in <module>
    "iotkey": decrypt_internal("f4dcd1511147af45775d7e680ac5312b"),  # noqa: E501
  File "/home/pi/.local/lib/python3.9/site-packages/midea_beautiful/midea.py", line 30, in decrypt_internal
    decryptor = cipher.decryptor()
  File "/home/pi/.local/lib/python3.9/site-packages/cryptography/hazmat/primitives/ciphers/base.py", line 135, in decryptor
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/home/pi/.local/lib/python3.9/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 6, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/home/pi/.local/lib/python3.9/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 63, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/home/pi/.local/lib/python3.9/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: libffi.so.7: cannot open shared object file: No such file or directory

**Comment by nbogojevic** [comment]
Hello @feliutg this is not related to this library, rather it means that libffi.so.7 is probably missing on your linux distribution. 

Here is one of discussions about this happening on raspberry pi:

https://community.home-assistant.io/t/python-install-on-raspberry-pi-os/241558/12

**Comment by feliutg** [comment]
Thanks for the help. I installed the libffi.so.7 and now it works. I knew it wasn't a library issue but probably people will run into the same issue. Thanks.
