### ISSUE TITLE
Partially working with Midea MA-12NXD0-I

### ISSUE THREAD

**Issue by dokatomi** [nbogojevic/midea-beautiful-air#13]
I wanted to automate my Midea AC with the openhab bindign, but it is not working.
Then I wanted to try the direct communication with this script.

If I execute this:
 midea-beautiful-air-cli status --ip 10.0.10.145 --token 388B14F891293....... --key EB84F8FF5FD3......

I receive this output:
```
WARNING:midea_beautiful.appliance:Midea B5 unknown property=b'@\x00'
WARNING:midea_beautiful.lan:Error getting device capabilities for sn=000000P0000000Q130B23717******** id=1979120933**** address=10.0.1***** version=3, cause Unable to send data after 3 retries, last error timed out for 000000P0000000Q130B23717******** (1979120933****)
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/midea_beautiful/lan.py", line 804, in identify
    responses = self._status(cmd, cloud if use_cloud else None)
  File "/home/user/.local/lib/python3.8/site-packages/midea_beautiful/lan.py", line 540, in _status
    responses = self.appliance_send(data)
  File "/home/user/.local/lib/python3.8/site-packages/midea_beautiful/lan.py", line 685, in appliance_send
    return self._appliance_send_8370(data)
  File "/home/user/.local/lib/python3.8/site-packages/midea_beautiful/lan.py", line 590, in _appliance_send_8370
    if packets := self._retry_send(original_data, response_buf):
  File "/home/user/.local/lib/python3.8/site-packages/midea_beautiful/lan.py", line 670, in _retry_send
    packets = self.appliance_send(data)
  File "/home/user/.local/lib/python3.8/site-packages/midea_beautiful/lan.py", line 685, in appliance_send
    return self._appliance_send_8370(data)
  File "/home/user/.local/lib/python3.8/site-packages/midea_beautiful/lan.py", line 590, in _appliance_send_8370
    if packets := self._retry_send(original_data, response_buf):
  File "/home/user/.local/lib/python3.8/site-packages/midea_beautiful/lan.py", line 675, in _retry_send
    raise MideaNetworkError(
midea_beautiful.exceptions.MideaNetworkError: Unable to send data after 3 retries, last error timed out for 000000P0000000Q130B23717******** (1979120933****)
id 000000P0000000Q130B23717.....
  id      = 19791....
  addr    = 10.0.10.145
  s/n     = 000000P0000000Q130B....
  model   = Air conditioner
  ssid    = net_ac_921F
  online  = True
  name    = 19791....
  running = True
  target  = 26.0
  indoor  = 27.2
  outdoor = 36.1
  fan     = 10
  mode    = 2
  purify  = False
  eco     = False
  sleep   = False
  F       = False
  error   = 0
  supports= {'eco': 1, 'has_no_wind_feel': 0, 'mode': 1, 'fan_swing': 1, 'electricity': 0, 'strong_fan': 1, 'fan_speed': 1, 'humidity': 3, 'temperature0': 32, 'temperature1': 60, 'temperature2': 32, 'temperature3': 60, 'temperature4': 32, 'temperature5': 60, 'temperature6': 5}
  version = 3
```

The printed values are ok from the ac, but the exception is why?
Can you please help me?

The set command also shows this exception, but the on/off command working, and the AC switches on/off.

**Comment by wojciewa** [comment]
I have noticed exactly this same behavior with Rotenso AC.

**Comment by mlb6** [comment]
I am also observing the same behaviour with a Carrier Infinity heat pump (40MPHAQ12XA3) using the midea usb wifi dongle.

**Comment by douggutaby** [comment]
Hi,

Same warning and error here. I use a Fisher AC, which is the same as the Midea Oasis Plus, and it is working with MSmartHome app.
