### ISSUE TITLE
Syntax Error when running 

### ISSUE THREAD

**Issue by gforums** [nbogojevic/midea-beautiful-air#18]
Good evening and welcome,

I tried to install your tool on a raspberry pi. Installation went trough with no issues. But when I try running your tool, it always fails with the following syntax error:

openhabian@openhabian:~ $ midea-beautiful-air-cli --help
Traceback (most recent call last):
  File "/home/openhabian/.local/bin/midea-beautiful-air-cli", line 5, in <module>
    from midea_beautiful.cli import cli
  File "/home/openhabian/.local/lib/python3.7/site-packages/midea_beautiful/__init__.py", line 6, in <module>
    from midea_beautiful.cloud import MideaCloud
  File "/home/openhabian/.local/lib/python3.7/site-packages/midea_beautiful/cloud.py", line 304
    if data := response.get("data", {}):
             ^
SyntaxError: invalid syntax

Anything I could try to fix that? Any known issues maybe with one of the depencies?

Thanks a lot, Christian

**Comment by luponata** [comment]
Same error, after fixing the typo a new import error appears:

```
  File "/usr/local/bin/midea-beautiful-air-cli", line 5, in <module>
    from midea_beautiful.cli import cli
  File "/usr/local/lib/python3.7/dist-packages/midea_beautiful/__init__.py", line 6, in <module>
    from midea_beautiful.cloud import MideaCloud
  File "/usr/local/lib/python3.7/dist-packages/midea_beautiful/cloud.py", line 14, in <module>
    from midea_beautiful.crypto import Security
  File "/usr/local/lib/python3.7/dist-packages/midea_beautiful/crypto.py", line 7, in <module>
    from typing import Any, Final, Tuple
ImportError: cannot import name 'Final' from 'typing' (/usr/lib/python3.7/typing.py)
```
