### ISSUE TITLE
Network error getting Token and Key

### ISSUE THREAD

**Issue by tteixeira** [nbogojevic/midea-beautiful-air#19]
When using both dscover or status command, i get always this following error (3 times). 

WARNING:midea_beautiful.lan:Error getting device capabilities for sn=000000P0000000Q1AC93C421******** id=14513553495**** address=192.168.***** version=3, cause Unable to send data after 3 retries, last error timed out for 000000P0000000Q1AC93C421******** (14513553495****)
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/midea_beautiful/lan.py", line 809, in identify
    responses = self._status(cmd, cloud if use_cloud else None)
  File "/home/pi/.local/lib/python3.9/site-packages/midea_beautiful/lan.py", line 540, in _status
    responses = self.appliance_send(data)
  File "/home/pi/.local/lib/python3.9/site-packages/midea_beautiful/lan.py", line 685, in appliance_send
    return self._appliance_send_8370(data)
  File "/home/pi/.local/lib/python3.9/site-packages/midea_beautiful/lan.py", line 590, in _appliance_send_8370
    if packets := self._retry_send(original_data, response_buf):
  File "/home/pi/.local/lib/python3.9/site-packages/midea_beautiful/lan.py", line 670, in _retry_send
    packets = self.appliance_send(data)
  File "/home/pi/.local/lib/python3.9/site-packages/midea_beautiful/lan.py", line 685, in appliance_send
    return self._appliance_send_8370(data)
  File "/home/pi/.local/lib/python3.9/site-packages/midea_beautiful/lan.py", line 590, in _appliance_send_8370
    if packets := self._retry_send(original_data, response_buf):
  File "/home/pi/.local/lib/python3.9/site-packages/midea_beautiful/lan.py", line 675, in _retry_send
    raise MideaNetworkError(
midea_beautiful.exceptions.MideaNetworkError: Unable to send data after 3 retries, last error timed out for 000000P0000000Q1AC93C421******** (14513553495****)

id 000000P0000000Q1AC93C421********/14513553495****
  id      = 145135534952750
  addr    = 192.168.1.201
  s/n     = 000000P0000000Q1AC93C421****
  model   = Air conditioner
  ssid    = net_ac_865A
  online  = True
  name    = AC - Living Room
  running = False
  target  = 24.0
  indoor  = 24.1
  outdoor = 19.0
  fan     = 101
  mode    = 1
  purify  = False
  eco     = False
  sleep   = False
  F       = False
  error   = 0
  supports= {'eco': 0, 'mode': 1, 'fan_swing': 1, 'electricity': 0, 'strong_fan': 1, 'fan_speed': 1, 'temperature0': 32, 'temperature1': 60, 'temperature2': 32, 'temperature3': 60, 'temperature4': 32, 'temperature5': 60, 'temperature6': 0}
  version = 3

Any idea why is this happening ?

**Comment by lovro995** [comment]
Me too.

**Comment by BernhardLinz** [comment]
I try to change the timeout (2 seconds) and retry settings (3 times) in the lan.py
It tooks longer but the error keeps

**Comment by BernhardLinz** [comment]
And the **Warning** comes with every command / option. So it works - but always with a warning header , ending with
`midea_beautiful.exceptions.MideaNetworkError: Unable to send data after 3 retries, last error timed out for`
and then comes the results

**Comment by douggutaby** [comment]
@BernhardLinz I did the similar with midea.py:
DEFAULT_RETRIES: Final = 1
DEFAULT_TIMEOUT: Final = 1
The error/warning is the same but I get response a little bit faster :)
