### ISSUE TITLE
fan_speed type error in air_conditioner

### ISSUE THREAD

**Issue by teleshoes** [nbogojevic/midea-beautiful-air#22]
```
user:~$ ~/.local/bin/midea-beautiful-air-cli set --ip 192.168.*.* --token FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF --key 9999999999999999999999999999999999999999999999999999999999999 --fan-speed 40
Traceback (most recent call last):
  File "/home/user/.local/bin/midea-beautiful-air-cli", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/midea_beautiful/cli.py", line 340, in cli
    return function(args)
           ^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/midea_beautiful/cli.py", line 263, in _run_set_command
    return _process_attr_arguments(args, appliance, cloud)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/midea_beautiful/cli.py", line 222, in _process_attr_arguments
    appliance.set_state(**set_args)
  File "/home/user/.local/lib/python3.11/site-packages/midea_beautiful/lan.py", line 848, in set_state
    self.apply(cloud)
  File "/home/user/.local/lib/python3.11/site-packages/midea_beautiful/lan.py", line 693, in apply
    cmd = self.state.apply_command()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/midea_beautiful/appliance.py", line 609, in apply_command
    cmd.fan_speed = self.fan_speed
    ^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/midea_beautiful/command.py", line 668, in fan_speed
    self.data[13] |= speed & 0b01111111
                     ~~~~~~^~~~~~~~~~~~
TypeError: unsupported operand type(s) for &: 'str' and 'int'
```

**Comment by teleshoes** [comment]
duplicate of #14
(still fixed in #23)
